//quemar la base de datos

let productos = [
    {
        nombre:"Aegis-One",
        fotos:["https://firebasestorage.googleapis.com/v0/b/tiendasurabs.appspot.com/o/nave1.jpg?alt=media&token=c6c022e4-618c-4999-a81e-f83e09940f98","https://firebasestorage.googleapis.com/v0/b/tiendasurabs.appspot.com/o/nave1.2.jpg?alt=media&token=4421e24c-6286-4706-8494-3db57bc1168f"],
        precio:2000000,
        popularidad:5,
        descripcion:"Una nave intrepida, equipada para soportar todas las condiciones extremas del vacio del espacio. Posee un sistema de reconocimiento por adn para que ningun amigo de lo ajeno se la lleve"
    },
    {
        nombre:"",
        fotos:["https://firebasestorage.googleapis.com/v0/b/tiendasurabs.appspot.com/o/nave2.jpg?alt=media&token=344eb4c2-d965-4221-bd3f-49ed2e54fbbc","https://firebasestorage.googleapis.com/v0/b/tiendasurabs.appspot.com/o/nave2.2.jpg?alt=media&token=a1c48ad8-0d24-4ec4-97ea-6e78e6b1e8a5"],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:["https://firebasestorage.googleapis.com/v0/b/tiendasurabs.appspot.com/o/nave3h.jpg?alt=media&token=6c8082b6-dc7c-4f37-bb83-b6d4d03280b9","https://firebasestorage.googleapis.com/v0/b/tiendasurabs.appspot.com/o/nave3.2.jpg?alt=media&token=edf5be91-c66e-4f86-a344-2aaf0af93dee"],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    }
]